### PR TITLE
Add tf-provider aiven-kafka-users

### PR DESCRIPTION
**Pull request by eversC**
This adds the new `terraform-provider-aiven-kafka-users` (which has cred rotation cababilities) to the terraform orb.

### CODE REVIEW

**Comment by eversC** [comment]
The change to the `rac-gcp-deploy` Dockerfile was to fix the build (piccolo.link...(?) became unavailable).

Switched to the official release, didn't change the sha256 checksum :D

**Comment by eversC** [comment]
> The change to the `rac-gcp-deploy` Dockerfile was to fix the build (piccolo.link...(?) for SBT became unavailable).
> 
> Switched to the official SBT release, didn't change the sha256 checksum being matched against :D

fixed in #164

**Review by apjm — APPROVED** [review]
Looks good

**Review by chris-brindley — APPROVED** [review]
LGTM

**Pull request merged**
