### PR TITLE
Set tag for ASP Deploy Orb

### PR DESCRIPTION
**Pull request by puzzledbytheweb**

### CODE REVIEW

**Review by EduardoLaranjo — COMMENTED** [review]
One thing that is making some confusion is the fact you have a default, so condition doesn't make much sense. What am I missing?

**Comment by puzzledbytheweb** [comment]
> One thing that is making some confusion is the fact you have a default, so condition doesn't make much sense. What am I missing?

An empty string is a falsey value, I just wanted to have a bit more control there but I guess it's redundant since not having a value is also falsey.

**Review by EduardoLaranjo — APPROVED** [review]
LGTM 🚀

**Comment by puzzledbytheweb** [comment]
Working in this PR - https://github.com/ovotech/circleci-orbs/pull/269

**Pull request closed without merging**
