### PR TITLE
Add npm authentication & shipit to versioned-lambda

### PR DESCRIPTION
**Pull request by Samuel-West**
NPM Auth:
* Adds optional step to `node-test-and-package` to authenticate with npm if a token is provided in the environment variables.
* Defaults to `true` because we assume that most projects that would use this orb would be using ovotech repositories.

Shipit:
* Adds `notify-shipit` optional step to `create-lambda-version`
* defaults to `false`

Readme updated to reflect new options.

### CODE REVIEW

**Comment by takac** [comment]
Would be worth updating the codeowners so you can merge stuff for this orb

**Comment by tom-g-dane** [comment]
> Would be worth updating the codeowners so you can merge stuff for this orb

Hey @takac , we are in the CODEOWNERS file, I specified the team name (https://github.com/orgs/ovotech/teams/orion-migration/discussions) of which we are both members but it still requests prod eng. Is there something not right about the way we defined that?

**Comment by takac** [comment]
Oh it should be in the .github dir!

**Comment by takac** [comment]
pushed a fix to master, now you have approval :)

**Comment by tom-g-dane** [comment]
Amazing thanks a lot @takac !

**Pull request merged**
