### PR TITLE
Update aiven provider versions

### PR DESCRIPTION
**Pull request by keirlawson**

### CODE REVIEW

**Comment by whyman** [comment]
Do we really need all of these? The docker image is already pretty beefy!

**Comment by keirlawson** [comment]
Probably not, I just need 1.3.5, can remove the others

**Comment by eversC** [comment]
Also worth noting the terraform aiven provider is broken for us for v1.2.2 and above. They've released a change that breaks our partially wildcarded ACLs, see #140

**Comment by keirlawson** [comment]
Closing in favour of #140

**Pull request closed without merging**
