### PR TITLE
add avn provider releases since 1.1.4

### PR DESCRIPTION
**Pull request by apjm**
There are a lot of tf_aiven_versions now

### CODE REVIEW

**Comment by eversC** [comment]
taking a look 👀

**Comment by eversC** [comment]
v1.2.2 (and later) of their provider is broken for us, see https://ovoenergy.slack.com/archives/G9S51FS8P/p1596041207331600

**Comment by apjm** [comment]
Oh dear. Thanks for looking At it Chris! I'll look at opening an issue in the provider repo. Setting up a call with one of their team for this week too so I'll talk about it there.

**Comment by takac** [comment]
Where is this at now?

**Comment by apjm** [comment]
Aiven agreed that suffix wildcards like _username_*_ are a valid construction and shouldn’t be excluded by their username validation. 
They made a change to allow suffix wildcards https://github.com/aiven/terraform-provider-aiven/pull/266 and cut a release. 
I tested the release with the aiven-as-code config. Got the same invalid non-alpha numeric username errors with the new release.
Two days ago they made another change to fix that https://github.com/aiven/terraform-provider-aiven/pull/276 
Just waiting for a release to test now.

**Comment by apjm** [comment]
We can't use a lot of these versions because they identify ACL usernames with a suffix wildcard as being invalid. Will be looking to update with newer versions when that issue is resolved. I.e. #154

**Pull request closed without merging**
