### PR TITLE
Handle exit code 5 for unsupported images

### PR DESCRIPTION
**Pull request by skjolber**
* Support for new status code 5, which is returned when image scanning cannot be performed. With an option to fail or not to fail if that is the case.
 * Support for unexpected status codes. 
 * Delete report after each image, if present
 * Less verbose, prints less to console. Results are present as artifacts, which is sufficient.

Note; I'm not very experienced in i bash scripts.

### CODE REVIEW

**Comment by eversC** [comment]
Hi @skjolber, thanks for your changes, and PR, and apologies for taking so long for us to review.

We'd like to make some minor changes, so I'll be pushing your fork to a branch in this repo that we can work from (that way we can keep your commits).

Some comments on the points you made:

> Support for new status code 5, which is returned when image scanning cannot be performed. With an option to fail or not to fail if that is the case.
Support for unexpected status codes.

This looks good, though some cleanup required in the bash script


> Delete report after each image, if present

We're already copying the report back out into a filename suffixed with the image name, so it seems to make sense to create a file following the same naming convention in the first place (that way we don't need to delete the report after each image scan).


> Less verbose, prints less to console. Results are present as artifacts, which is sufficient.

Could make it configurable? I know some users appreciate having the console output to view in their CI/CD jobs, for example.

**Comment by skjolber** [comment]
Great to see this is making progress. Will you make the final adjustments from here on?

> > Support for new status code 5, which is returned when image scanning cannot be performed. With an option to fail or not to fail if that is the case.
> > Support for unexpected status codes.
> 
> This looks good, though some cleanup required in the bash script
> 
Good! I'll gladly admit bash scripting is something I must google every time so far.

> > Delete report after each image, if present
> 
> We're already copying the report back out into a filename suffixed with the image name, so it seems to make sense to create a file following the same naming convention in the first place (that way we don't need to delete the report after each image scan).
> 
Sounds good. 

> > Less verbose, prints less to console. Results are present as artifacts, which is sufficient.
> 
> Could make it configurable? I know some users appreciate having the console output to view in their CI/CD jobs, for example.

Yes, thats probably a good idea. We're scanning a lot of images (per job), and although its a pain to download the console output to view the end result, from time to time the scan fails (freezes), and then I'd like more console output.

**Comment by skjolber** [comment]
@eversC any progress?

**Comment by eversC** [comment]
Hi @skjolber, I'm almost there. There's not been much change required on top of the changes you've made, I'm just dealing with the use-cases of having console Vs. file output enabled.

My colleague @danielflookovo who can review the changes is currently away but back early next week so I'll look to get these changes finished off end of this week and discuss with him.

**Comment by skjolber** [comment]
Hi @danielflookovo, any progress?

**Comment by skjolber** [comment]
@eversC @danielflookovo if file output vs console is an issue, save that for the next version (its been two months now).

**Comment by eversC** [comment]
Hey @skjolber 

Apologies again for this dragging on, and thanks for your patience. See #70 for all the changes (including yours). As such I'm closing this PR now

**Pull request closed without merging**
