### PR TITLE
Add TF 0.13 executor

### PR DESCRIPTION
**Pull request by takac**
Also removed the old aiven tf providers

### CODE REVIEW

**Review by mattslane — APPROVED** [review]

**Comment by whyman** [comment]
Do we need to bundle any executors? Perhaps we could make them available somewhere to allow them to be used via the new "Automatic installation of third-party providers" functionality?

**Comment by takac** [comment]
If you mean "providers" rather than "executors" I think that's a good idea! Wasn't aware of that feature.

**Comment by takac** [comment]
@whyman there might be an issue with that.. do Aiven host a terraform registry? The auto-install requires a true registry rather than just an s3 bucket from what I've read

**Comment by whyman** [comment]
I would hope that Aiven would add their provider to the hashicorp provider registry.

It looks like you can publish providers directly to the hashicorp registry (https://registry.terraform.io/publish/provider).

So initally perhaps we could upload an `ovotech/aiven` provider, until the `aiven/aiven` provider is available.

**Comment by takac** [comment]
Someone else is already doing this 🤦 https://registry.terraform.io/providers/juniorz/aiven/latest

Is the `kafka-users` provider hosted in our terraform registry (and is it accessible)?

Maybe we revisit this when these are in a registry

**Comment by takac** [comment]
I asked Aiven about getting their provider in the official registry

> Yes, we are currently are working on that! There is a process that we must follow to become HashiCorp approved Terraform Provider and our Terraform team is working on making the required changes to existing one. We are expecting to have it available after Aiven Terraform Provider v2 release. I will add your contact information and we will let you know once the process is complete.

**Comment by takac** [comment]
Lets cut another release when we make that change to remove those providers

**Pull request merged**
