### PR TITLE
Add HCL syntax highlighting for Terraform plan GitHub comment

### PR DESCRIPTION
**Pull request by gordonkeogh**

### CODE REVIEW

**Comment by dflook** [comment]
This is a great idea. I think you'll also need to add it to the regex on line 72.

**Comment by eversC** [comment]
I guess it needs to be an optional "hcl" to make it back compat, and a non-capture group so if "hcl" is present it doesn't knock the use of the groups off kilter

instead of what we have now:

```
'{re.escape(self._comment_identifier)}\n```(.*?)```(.*)'
```

we could have something like this?:

```
'{re.escape(self._comment_identifier)}\n```(?:hcl)?(.*?)```(.*)'
```

**Comment by whyman** [comment]
@gordonspark can you rebase this to pull in the terraform orb fix?

**Comment by gordonkeogh** [comment]
@whyman Seem to be having an issue with the `clair-scanner` orb on [CircleCI](https://app.circleci.com/pipelines/github/ovotech/circleci-orbs?branch=terraform-add-syntax-highlighting-github-comment)

**Comment by whyman** [comment]
@gordonkeogh one more rebase, please :+1:

**Review by whyman — APPROVED** [review]

**Comment by eversC** [comment]
(note this was reverted ^^)

ah, think it was just missing a question mark from the regex

```'{re.escape(self._comment_identifier)}\n```(?:hcl)(.*?)```(.*)'```

should have been:

```'{re.escape(self._comment_identifier)}\n```(?:hcl)?(.*?)```(.*)'```

(question mark missing from after `(?:hcl)`)

**Pull request merged**
