### PR TITLE
Make Terraform Plan Comments Collapsible

### PR DESCRIPTION
**Pull request by Adam-McDevitt**
Good afternoon

Terraform plan comments can get pretty long sometimes, so I thought this would be useful.

The plans would be open by default and can be collapsed.

They look like this:

Terraform plan for __non-prod-cluster__
<details open>
<summary>Plan</summary>

```hcl
No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.

Warning: Version constraints inside provider configuration blocks are deprecated

  on cluster/main.tf line 29, in provider "aws":
  29:   version = ">= 2.28.1"

Terraform 0.13 and earlier allowed provider version constraints inside the
provider configuration block, but that is now deprecated and will be removed
in a future version of Terraform. To silence this warning, move the provider
version constraint into the required_providers block.

Releasing state lock. This may take a few moments...
```
</details>

Plan generated in CircleCI Job [non-prod-plan 991](https://circleci.com/gh/ovotech/smart-bookings-terraform/991)

### CODE REVIEW

**Comment by Adam-McDevitt** [comment]
Unfortunately the "summary" in the dropdown doesn't support formatting so I would've had to remove the __bold__ on "Terraform plan for __whatever__" if I wanted to use that for the summary.

**Review by takac — APPROVED** [review]

**Review by takac — CHANGES_REQUESTED** [review]
Could you please bump the minor version

**Review by takac — APPROVED** [review]

**Comment by Adam-McDevitt** [comment]
@takac is this fine to be merged? I don't have merge permissions myself.

**Review by connelldave — APPROVED** [review]

**Comment by connelldave** [comment]
Hey @Adam-McDevitt - sorry this fell through the cracks with Tom leaving last week.

**Pull request merged**
