### PR TITLE
Terraform: search for backend-config and var-file in module path too

### PR DESCRIPTION
**Pull request by redbaron**
Backwards compatible change to search for backend config file relative to module path

### CODE REVIEW

**Comment by whyman** [comment]
Could you not just set `parameters.backend_config_file` to have a path in it?

**Comment by redbaron** [comment]
> Could you not just set `parameters.backend_config_file` to have a path in it?

> Could you not just set parameters.backend_config_file to have a path in it?

Yes, that's the current workaround, but it is counter intuitive, at least for me. `path` specifies main configuration path and rest of parameters should be relative to it, as if you do `cd <<paremeters.path>>` and rest of terraform commands run from there.

**Comment by whyman** [comment]
Lets at least add something to the docs too then?

**Comment by redbaron** [comment]
> Lets at least add something to the docs too then?

Added note about relative paths to  the readme

**Pull request merged**
