### PR TITLE
Fix authorization bearer for existing terraform version

### PR DESCRIPTION
**Pull request by eversC**
from #479 fork

### CODE REVIEW

**Comment by eversC** [comment]
did the `/versions` endpoint get made private at some point?

I think we may need to bump the orb version here too

Does the same change need to be made to the `terraform-v2` orb?

**Comment by drewhemm** [comment]
Yes, the same change needs to be made to `terraform-v2` - apolologies, as the PR should have included both. I have pushed a second commit to my fork

**Comment by eversC** [comment]
> Yes, the same change needs to be made to `terraform-v2` - apolologies, as the PR should have included both. I have pushed a second commit to my fork

looks good

I think the orb versions (+changelogs) need updating, as that way the changes will get automatically released when we merge.

**Comment by drewhemm** [comment]
I've updated my fork with the changes to the orb versions and changelogs:

https://github.com/drewhemm/circleci-orbs/commit/8aa1388bacef6ea40fbc5a394d7b191d42a867a6

**Review by mattslane — APPROVED** [review]

**Pull request merged**
